version: '2'
services:
  babelindex:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
      
  engine:
    build: .
    ports:
      - "3002:3002"
    environment:
      - BB_ELASTIC_HOST=babelindex:9200
    external_links:
      - babelindex:babelindex
